ゲームオブジェクト基底クラスの作成 #17の修正
human-osaka-game-2018/Summoners-Aster pull request #22
Opened 2019-03-19 13:56 UTC by rikita-fujizono

## 元Issue

Closes #12 

## 変更内容

- [x] パスの修正
- [x] ファイルの終わりに改行を入れるように修正
- [x] デストラクタを仮想関数に変更
- [x] クラスをnamespaceの中に入れるよう変更
## 影響範囲

無し
## 補足

#17 の修正

2019-03-19 14:12 UTC, Harutaka-Tsujino commented on Summoners-Aster/ObjectIntegrator/Object/Object.cpp
> +namespace summoners_aster
Googleのスタイルガイドに従うならsummonersaster

2019-03-19 14:26 UTC, taishi-matsumura commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.h
> +		friend Singleton<SceneSwitcher>;
基底クラスをfriendに指定してる理由は？

2019-03-19 14:26 UTC, taishi-matsumura commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.h
> +		std::map<Scene::KINDS, Scene*> m_pScenes;
僕もmap好きなのでよく使いますが、ソート処理を考慮しないのであればunordered mapの方が良いみたいですよ。
違いを調べてみてください。

2019-03-19 14:29 UTC, taishi-matsumura requested changes

2019-03-19 14:29 UTC, taishi-matsumura commented on Summoners-Aster/ObjectIntegrator/Object/Object.h
> +		inline float GetZ() const
せめて基底クラスやinterfaceクラスのpublicメソッドにはコメント入れておきましょう

2019-03-19 14:33 UTC, Harutaka-Tsujino commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.h
> +		friend Singleton<SceneSwitcher>;
Singleton基底クラスの関数にSceneSwitcher
をインスタンス化させる関数があるのでfriendにしています

2019-03-19 14:35 UTC, Harutaka-Tsujino commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.h
> +		std::map<Scene::KINDS, Scene*> m_pScenes;
そうですねソートする予定もないのでそちらのほうがいいと思います

2019-03-19 14:36 UTC, taishi-matsumura commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.h
> +		friend Singleton<SceneSwitcher>;
基底クラスが派生クラスを作るのかぁ。
なんか凄い作りやな…

2019-03-19 14:42 UTC, taishi-matsumura reviewed
教えてクンですみません

2019-03-19 14:42 UTC, taishi-matsumura commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.cpp
> +			pScene.second->Finalize();
mapは好きなのですが、first/secondとかは大嫌いです。C#のdictionaryのkey/valueでギリギリ。

autoで受け取る型をうまく書けばこれを隠せるみたいですが、C++11では無理なのかな？17から？

2019-03-19 14:47 UTC, taishi-matsumura requested changes

2019-03-19 14:47 UTC, taishi-matsumura commented on Summoners-Aster/SceneSwitcher/Scene/Scene.h
> +		enum class KINDS
型名は単数形の方が良いと思いますよ。
下記のEnumのセクションを読んでみてください。
https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces

2019-03-19 15:03 UTC, Harutaka-Tsujino commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.cpp
> +			pScene.second->Finalize();
調べてみましたがどの記事もfirstとsecond使ってましたね

2019-03-19 15:06 UTC, rikita-fujizono commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.h
> +		std::map<Scene::KINDS, Scene*> m_pScenes;
unordered_mapに変更しました。

2019-03-19 15:06 UTC, taishi-matsumura commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.cpp
> +			pScene.second->Finalize();
「構造化束縛」ってやつですね。
https://qiita.com/leon-joel/items/81415c1ef355c6246280

 C++17でした…

2019-03-19 15:10 UTC, taishi-matsumura commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.cpp
> +			pScene.second->Finalize();
これ使うと下記のようなステキなループになります。
https://qiita.com/_EnumHack/items/f462042ec99a31881a81#map%E3%81%AE%E3%82%A4%E3%83%86%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3

17か…

2019-03-19 15:11 UTC, Harutaka-Tsujino commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.cpp
> +			pScene.second->Finalize();
```suggestion
		for (auto& pScene[second] : m_pScenes)
		{
			pScene->Finalize();
```
こんな感じですかね

2019-03-19 15:12 UTC, taishi-matsumura commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.cpp
> +			pScene.second->Finalize();
それそれ。17やからやめとこう。

2019-03-19 15:17 UTC, rikita-fujizono commented on Summoners-Aster/SceneSwitcher/Scene/Scene.h
> +		enum class KINDS
型名を単数形に変更しました。

2019-03-19 15:18 UTC, Harutaka-Tsujino commented on Summoners-Aster/SceneSwitcher/SceneSwitcher.cpp
> +			pScene.second->Finalize();
なるほど

2019-03-19 17:21 UTC, rikita-fujizono commented on Summoners-Aster/ObjectIntegrator/Object/Object.h
> +		inline float GetZ() const
コメントの追加のコミットで修正しました。

2019-03-19 17:35 UTC, taishi-matsumura approved these changes
インデント以外、僕からはありません

2019-03-19 17:35 UTC, taishi-matsumura commented on Summoners-Aster/SceneSwitcher/Scene/Scene.h
> +	    /// </summary>
インデントずれ

2019-03-20 02:00 UTC, rikita-fujizono commented on Summoners-Aster/SceneSwitcher/Scene/Scene.h
> +	    /// </summary>
コメントの修正のコミットで直しました。

2019-03-20 02:12 UTC, merged