カード効果機能 【WIP】
human-osaka-game-2018/Summoners-Aster pull request #65
Opened 2019-04-16 13:05 UTC by ToshiyaMatsuoka

## 元Issue

Closes #64

## 変更内容

- [ ] カード効果を使用できるようにする
- [ ] カード効果を起動させる
- [ ] カード効果を実行させる

## 影響範囲

## 補足

2019-04-18 04:29 UTC, ToshiyaMatsuoka commented
![image](https://user-images.githubusercontent.com/39691763/56331781-b9332100-61c8-11e9-8cb5-9b926d878b9e.png)

2019-04-26 13:37 UTC, Harutaka-Tsujino reviewed
スペル以外はいいと思います
erとorの使い分けが分からなかったので調べたやつ貼っときます
https://ameblo.jp/cospoli/entry-10328957322.html

2019-04-26 13:37 UTC, Harutaka-Tsujino commented on Summoners-Aster/Card/Ability/Ability.h
> +	enum Execute
動作だけでなく種類というのを明示した名前のほうがいいと思います

2019-04-26 13:37 UTC, Harutaka-Tsujino commented on Summoners-Aster/Card/Ability/CardAbilityMediator.cpp
> +	std::vector<Card*> CardAbilityMediator::m_pRegistedCards;
```suggestion
	std::vector<Card*> CardAbilityMediator::m_pRegisteredCards;
```

2019-04-26 13:37 UTC, Harutaka-Tsujino commented on Summoners-Aster/Card/Ability/CardAbilityMediator.cpp
> +bool CardAbilityMediator::Activateor(ActivationEvent activationEvent)
```suggestion
bool CardAbilityMediator::Activator(ActivationEvent activationEvent)
```

2019-04-26 13:37 UTC, Harutaka-Tsujino commented on Summoners-Aster/Card/Ability/CardAbilityMediator.cpp
> +bool CardAbilityMediator::Unregistor(Card* pCard)
```suggestion
bool CardAbilityMediator::Unregister(Card* pCard)
```

2019-04-26 13:37 UTC, Harutaka-Tsujino commented on Summoners-Aster/Card/Card.h
> +		Ability m_Ability;
ここのファイルはlowerでお願いします

2019-04-27 01:28 UTC, ToshiyaMatsuoka commented on Summoners-Aster/Card/Ability/CardAbilityMediator.cpp
> +	std::vector<Card*> CardAbilityMediator::m_pRegistedCards;
修正しました

2019-04-27 01:30 UTC, ToshiyaMatsuoka commented on Summoners-Aster/Card/Ability/CardAbilityMediator.cpp
> +bool CardAbilityMediator::Activateor(ActivationEvent activationEvent)
修正しました

2019-04-27 01:30 UTC, ToshiyaMatsuoka commented on Summoners-Aster/Card/Ability/CardAbilityMediator.cpp
> +bool CardAbilityMediator::Unregistor(Card* pCard)
修正しました

2019-04-27 01:30 UTC, ToshiyaMatsuoka commented on Summoners-Aster/Card/Card.h
> +		Ability m_Ability;
修正しました

2019-04-27 08:37 UTC, Harutaka-Tsujino requested changes

2019-04-27 08:37 UTC, Harutaka-Tsujino commented on Summoners-Aster/Card/Ability/CardAbilityMediator.cpp
> +bool CardAbilityMediator::Registor(Card* pCard)
Unregisterと同様にregisterですね

2019-04-28 00:53 UTC, ToshiyaMatsuoka commented on Summoners-Aster/Card/Ability/CardAbilityMediator.cpp
> +bool CardAbilityMediator::Registor(Card* pCard)
修正しました

2019-04-28 06:33 UTC, Harutaka-Tsujino approved these changes
確認しました

2019-04-30 11:53 UTC, merged